/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsPackagesRouteImport } from './routes/products/packages'
import { Route as ProtectedRecordsRouteImport } from './routes/_protected/records'
import { Route as ProtectedPatientDashboardRouteImport } from './routes/_protected/patient-dashboard'
import { Route as ProtectedNewRecordRouteImport } from './routes/_protected/new-record'
import { Route as ProtectedFavoritesRouteImport } from './routes/_protected/favorites'
import { Route as ProtectedAppointmentsRouteImport } from './routes/_protected/appointments'
import { Route as ProtectedSettingsPageRouteImport } from './routes/_protected/SettingsPage'
import { Route as ProtectedRecordsPageRouteImport } from './routes/_protected/RecordsPage'
import { Route as ProtectedPatientsPageRouteImport } from './routes/_protected/PatientsPage'
import { Route as ProtectedAnalyticsPageRouteImport } from './routes/_protected/AnalyticsPage'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/AdminDashboard'
import { Route as ProtectedDoctorDetailDoctorIdRouteImport } from './routes/_protected/DoctorDetail.$doctorId'

const CartLazyRouteImport = createFileRoute('/cart')()

const CartLazyRoute = CartLazyRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cart.lazy').then((d) => d.Route))
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPackagesRoute = ProductsPackagesRouteImport.update({
  id: '/products/packages',
  path: '/products/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRecordsRoute = ProtectedRecordsRouteImport.update({
  id: '/_protected/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPatientDashboardRoute =
  ProtectedPatientDashboardRouteImport.update({
    id: '/_protected/patient-dashboard',
    path: '/patient-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedNewRecordRoute = ProtectedNewRecordRouteImport.update({
  id: '/_protected/new-record',
  path: '/new-record',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFavoritesRoute = ProtectedFavoritesRouteImport.update({
  id: '/_protected/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppointmentsRoute = ProtectedAppointmentsRouteImport.update({
  id: '/_protected/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsPageRoute = ProtectedSettingsPageRouteImport.update({
  id: '/_protected/SettingsPage',
  path: '/SettingsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRecordsPageRoute = ProtectedRecordsPageRouteImport.update({
  id: '/_protected/RecordsPage',
  path: '/RecordsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPatientsPageRoute = ProtectedPatientsPageRouteImport.update({
  id: '/_protected/PatientsPage',
  path: '/PatientsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAnalyticsPageRoute = ProtectedAnalyticsPageRouteImport.update({
  id: '/_protected/AnalyticsPage',
  path: '/AnalyticsPage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/_protected/AdminDashboard',
  path: '/AdminDashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDoctorDetailDoctorIdRoute =
  ProtectedDoctorDetailDoctorIdRouteImport.update({
    id: '/_protected/DoctorDetail/$doctorId',
    path: '/DoctorDetail/$doctorId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof CartLazyRoute
  '/AdminDashboard': typeof ProtectedAdminDashboardRoute
  '/AnalyticsPage': typeof ProtectedAnalyticsPageRoute
  '/PatientsPage': typeof ProtectedPatientsPageRoute
  '/RecordsPage': typeof ProtectedRecordsPageRoute
  '/SettingsPage': typeof ProtectedSettingsPageRoute
  '/appointments': typeof ProtectedAppointmentsRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/new-record': typeof ProtectedNewRecordRoute
  '/patient-dashboard': typeof ProtectedPatientDashboardRoute
  '/records': typeof ProtectedRecordsRoute
  '/products/packages': typeof ProductsPackagesRoute
  '/DoctorDetail/$doctorId': typeof ProtectedDoctorDetailDoctorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof CartLazyRoute
  '/AdminDashboard': typeof ProtectedAdminDashboardRoute
  '/AnalyticsPage': typeof ProtectedAnalyticsPageRoute
  '/PatientsPage': typeof ProtectedPatientsPageRoute
  '/RecordsPage': typeof ProtectedRecordsPageRoute
  '/SettingsPage': typeof ProtectedSettingsPageRoute
  '/appointments': typeof ProtectedAppointmentsRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/new-record': typeof ProtectedNewRecordRoute
  '/patient-dashboard': typeof ProtectedPatientDashboardRoute
  '/records': typeof ProtectedRecordsRoute
  '/products/packages': typeof ProductsPackagesRoute
  '/DoctorDetail/$doctorId': typeof ProtectedDoctorDetailDoctorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/cart': typeof CartLazyRoute
  '/_protected/AdminDashboard': typeof ProtectedAdminDashboardRoute
  '/_protected/AnalyticsPage': typeof ProtectedAnalyticsPageRoute
  '/_protected/PatientsPage': typeof ProtectedPatientsPageRoute
  '/_protected/RecordsPage': typeof ProtectedRecordsPageRoute
  '/_protected/SettingsPage': typeof ProtectedSettingsPageRoute
  '/_protected/appointments': typeof ProtectedAppointmentsRoute
  '/_protected/favorites': typeof ProtectedFavoritesRoute
  '/_protected/new-record': typeof ProtectedNewRecordRoute
  '/_protected/patient-dashboard': typeof ProtectedPatientDashboardRoute
  '/_protected/records': typeof ProtectedRecordsRoute
  '/products/packages': typeof ProductsPackagesRoute
  '/_protected/DoctorDetail/$doctorId': typeof ProtectedDoctorDetailDoctorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctors'
    | '/login'
    | '/register'
    | '/cart'
    | '/AdminDashboard'
    | '/AnalyticsPage'
    | '/PatientsPage'
    | '/RecordsPage'
    | '/SettingsPage'
    | '/appointments'
    | '/favorites'
    | '/new-record'
    | '/patient-dashboard'
    | '/records'
    | '/products/packages'
    | '/DoctorDetail/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctors'
    | '/login'
    | '/register'
    | '/cart'
    | '/AdminDashboard'
    | '/AnalyticsPage'
    | '/PatientsPage'
    | '/RecordsPage'
    | '/SettingsPage'
    | '/appointments'
    | '/favorites'
    | '/new-record'
    | '/patient-dashboard'
    | '/records'
    | '/products/packages'
    | '/DoctorDetail/$doctorId'
  id:
    | '__root__'
    | '/'
    | '/doctors'
    | '/login'
    | '/register'
    | '/cart'
    | '/_protected/AdminDashboard'
    | '/_protected/AnalyticsPage'
    | '/_protected/PatientsPage'
    | '/_protected/RecordsPage'
    | '/_protected/SettingsPage'
    | '/_protected/appointments'
    | '/_protected/favorites'
    | '/_protected/new-record'
    | '/_protected/patient-dashboard'
    | '/_protected/records'
    | '/products/packages'
    | '/_protected/DoctorDetail/$doctorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CartLazyRoute: typeof CartLazyRoute
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAnalyticsPageRoute: typeof ProtectedAnalyticsPageRoute
  ProtectedPatientsPageRoute: typeof ProtectedPatientsPageRoute
  ProtectedRecordsPageRoute: typeof ProtectedRecordsPageRoute
  ProtectedSettingsPageRoute: typeof ProtectedSettingsPageRoute
  ProtectedAppointmentsRoute: typeof ProtectedAppointmentsRoute
  ProtectedFavoritesRoute: typeof ProtectedFavoritesRoute
  ProtectedNewRecordRoute: typeof ProtectedNewRecordRoute
  ProtectedPatientDashboardRoute: typeof ProtectedPatientDashboardRoute
  ProtectedRecordsRoute: typeof ProtectedRecordsRoute
  ProductsPackagesRoute: typeof ProductsPackagesRoute
  ProtectedDoctorDetailDoctorIdRoute: typeof ProtectedDoctorDetailDoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/packages': {
      id: '/products/packages'
      path: '/products/packages'
      fullPath: '/products/packages'
      preLoaderRoute: typeof ProductsPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/records': {
      id: '/_protected/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof ProtectedRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/patient-dashboard': {
      id: '/_protected/patient-dashboard'
      path: '/patient-dashboard'
      fullPath: '/patient-dashboard'
      preLoaderRoute: typeof ProtectedPatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/new-record': {
      id: '/_protected/new-record'
      path: '/new-record'
      fullPath: '/new-record'
      preLoaderRoute: typeof ProtectedNewRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/favorites': {
      id: '/_protected/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ProtectedFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/appointments': {
      id: '/_protected/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof ProtectedAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/SettingsPage': {
      id: '/_protected/SettingsPage'
      path: '/SettingsPage'
      fullPath: '/SettingsPage'
      preLoaderRoute: typeof ProtectedSettingsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/RecordsPage': {
      id: '/_protected/RecordsPage'
      path: '/RecordsPage'
      fullPath: '/RecordsPage'
      preLoaderRoute: typeof ProtectedRecordsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/PatientsPage': {
      id: '/_protected/PatientsPage'
      path: '/PatientsPage'
      fullPath: '/PatientsPage'
      preLoaderRoute: typeof ProtectedPatientsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/AnalyticsPage': {
      id: '/_protected/AnalyticsPage'
      path: '/AnalyticsPage'
      fullPath: '/AnalyticsPage'
      preLoaderRoute: typeof ProtectedAnalyticsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/AdminDashboard': {
      id: '/_protected/AdminDashboard'
      path: '/AdminDashboard'
      fullPath: '/AdminDashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/DoctorDetail/$doctorId': {
      id: '/_protected/DoctorDetail/$doctorId'
      path: '/DoctorDetail/$doctorId'
      fullPath: '/DoctorDetail/$doctorId'
      preLoaderRoute: typeof ProtectedDoctorDetailDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CartLazyRoute: CartLazyRoute,
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAnalyticsPageRoute: ProtectedAnalyticsPageRoute,
  ProtectedPatientsPageRoute: ProtectedPatientsPageRoute,
  ProtectedRecordsPageRoute: ProtectedRecordsPageRoute,
  ProtectedSettingsPageRoute: ProtectedSettingsPageRoute,
  ProtectedAppointmentsRoute: ProtectedAppointmentsRoute,
  ProtectedFavoritesRoute: ProtectedFavoritesRoute,
  ProtectedNewRecordRoute: ProtectedNewRecordRoute,
  ProtectedPatientDashboardRoute: ProtectedPatientDashboardRoute,
  ProtectedRecordsRoute: ProtectedRecordsRoute,
  ProductsPackagesRoute: ProductsPackagesRoute,
  ProtectedDoctorDetailDoctorIdRoute: ProtectedDoctorDetailDoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
